sudo: true
language: node_js
node_js:
- '8'
script:
- cd _generator
- bash ./deploy.sh
branches:
  only:
  - master
env:
  global:
    secure: FzyfAEIk9YttzYMCb+NPVGDvjdllvb5b+ixdMy3QDDC8E7B8UkHQGqBe4ZKUhHuQ/HqBmwFLloJml4DaCMEkl8axgRBgMoeSwU/xOJwxbuJQPsSVjPXAezlSgBan+ABAcJoi/b1h0UcquFfKgVNm+R1xlkoFlFxTOxxc0W3I4IIoJcS1alQmQLVrYUClVsKInyFit+ijvYZZA87lwLW7QWfGKDXjyQ61GVJKF0geF2rkaHKUWgWAMb1LccJE16VC0eHYWrx5rVCvzD+dwYS5d7oz7JAO9woUTIeEbavsJeTa5NvXD5EZO5jYdLi6JojckFLIbxSqVxdU7TvGKtuaIIor0KzZu7tMgU1C0Ivjji/MhdTNkMp/deaCxXv7lJE547M4gG3NWtbYSs1yPWXhv1HsXsvrGWQTsmNs9e5NPJ7sULk2PdUhO0j7WQxAmNoZ2tEAXQfPAc9C9f6SGEa+uMDRsez0ZvUs89kzK2dv0Uq66j0CItfMyax+/KVqfrWZfFDvzgIFvp410TpZYqfyR/jyQLOum3QhBcAUd8gF2ZOZJAB2TOSKLSgz6X7Cu7AYeV37hxPJLVgOLp5+1i7Y8859XLrIP2YFzUMv1KHZWcuXuWtb2TtsQnxMLFPqrR2qUCf0INC3YSTeClZm7JL86i1+X2eGUQ9muAY2cTTWPhQ=
