sudo: true
language: node_js
node_js:
- '8'
script:
- bash ./deploy.sh
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/openactive/openactive.github.io.git
  - secure: D3TYo1io5x5BeKOLtzvPKClIk7eUg+8/WK1dwGoV5aizXIuMFH91uZudeyr2SvttrZib8FOK2oUiOmOd5eGJAMbPNVCbLOrbGhBz7cva0fpWfqtWb5gDJYnAxmDOYf6W4RjphyguULHNPos1Y+0fJLWVnlRTw00gyAwoKUlZw1R8Pas1dsv9ukAQNYqDUqq39CxOuJKZjQa6KD8qO8PyJz3NUzXA58knBfTiSgKXav9cT7NStQ5LfYnSRIg2ug6jfxEosfeUt/JK/0OfeKX8QH9nITQ8pZLgLq4y/ADKawQc5P0fbBqQXb/wbwwWi7IP6O/ufbpZToVpeen1vyY5bwyJyprFOQwL9EkhJ9FGUqLZuQvvXUEcKgF+U+gJAmTSbZHqoDxI6FZGgPQamRASp8EWGCUfdMHeMsEiW4nOZpMdCJrK6i2mnSymDpl622j4QSp2GRjuN4MHHwYgGXf3UA+1N2DhPhNL1oa4RN89S/yi329+a9UemTUt26eSgKuai3BIdBneHL4zgRaP2LYC156XSxIQZcLqbguK7vI7YIAxwAhDqV2nFKKuEqR/NVQZclWtLNFREnJWo8mkcZVa5vKa2tW5i5rdvDQYLrlJ0VKIXSvQmTBJWHpwZgXN0knES8G05IdJFFktmvD+7Z6PO/marAKq75K7rDSqoFdTQN0=
